### ISSUE TITLE
fourfront? 4front?

### ISSUE THREAD

**Issue by burakalver** [4dn-dcic/fourfront#106]
Do we like "fourfront" as the name for the 4DN front end repo? If yes, we can go ahead and rename it.

**Comment by burakalver** [comment]
Is there anything else that needs to be done for this?

**Comment by j1z0** [comment]
probably should go ahead and search replace encode for fourfront, throughout the entire project and make the renaming proper like.

**Comment by KorayKirli** [comment]
There might be some cases where ENC is also used, if you want to change with FDN or FourF.
