### ISSUE TITLE
publication schema to support abstract/manuscript tracking for the consortium

### ISSUE THREAD

**Issue by ngehlenborg** [4dn-dcic/fourfront#127]
In order to implement the abstract/manuscript tracking system directly within the 4DN Data Portal (currently at https://sites.google.com/site/4dndawiki/working-groups-list/publication-policy-wg/manuscripts), we will need to support the following fields in the publication schema:
1. Abstract
2. Contact author(s)
   1. Name
   2. Email
3. Status: `In preparation`, `Submitted`, `Published`
4. Creation Date
5. Last Modification Date

**To resolve potential conflicts among consortium members, it needs to be possible to go back to any previous version of the entry.**

We should also think about a mechanism that would prevent publications with status other than `Published` from being made publicly (outside the consortium) accessible on the data portal.

**Comment by burakalver** [comment]
Going back to previous versions is not natively possible with snovault. We can hack it by treating each edit as a new submission and relating different versions of the same abstract; using the same mechanism that we have for experiment_relation.

Controlling viewing rights based on status should be easy. We plan to have a better understanding of this in practise this week with data/experiment submissions.

Depending on the urgency, we can work on this in ~2 weeks.
