### ISSUE TITLE
Submitting embedded sub-objects and referencing inserts below in the excel

### ISSUE THREAD

**Issue by KorayKirli** [4dn-dcic/fourfront#153]
When the fields.xls is created from schemas, embedded subobjects are not broken down to individual components, like experiment relations.
It is now a single fields "experiment_relations".
It should be called "experiment_relations.relationship_type" and "experiment_relations.experiment"
For the time being, I changed it by hand where ever required, and did not manage to implement it in the script.

a second issue is the references to inserts that are not yet created. If you have a set of experiments exp1 exp2 exp3 ... in the experiment sheet, it is not possible to put a relation to exp2 in exp1 since it is not created yet. We need the loadxl.py like field skipping and a second cycle of patch. Right now I made it such that I avoid a problematic ordering.

**Comment by KorayKirli** [comment]
I have a solution idea for this problem

1)whenever there is such a field, we accumulate these cases in a list of "sheet,field"
listoffields=[
    ["experimenthic", "related_experiments"],
    ["experimentset", "experiments_in_this_set"]
    [biosample, related_biosample]
    ["file", "related_file"]
]

2) when we create the excel, we skip this columns = excel1.xls
3) write these fields in another excel with alias column added= excel2.xls

4) then in the background this is run:
python3 import_data.py excel1.xls --update
python3 import_data.py excel2.xls --patch

should work and possibly easy to make, what do you think @j1z0?
ps: I tried to write the code myself but gave up after sometime, became time consuming for me

**Comment by j1z0** [comment]
@KorayKirli  - ok so I pushed a couple of fixes related to this to the Wranglers repo.  First one generates the embeded fields.  Second one will check if you have aliases and use the first one to check and see if the record exists, if so it will ask you to patch.  With those your suggested solution should work, albeit with the manual work of creating the two files.  If your happy with that we can close this issue.

If however you want me to add some additional magic to try and do the update then patch automagically then comment here and I'll do that as well. I'll wait to hear from you and work on something else for the time being.

**Comment by aschroed** [comment]
@j1z0 I think there might be a small bug/issue in the embedded fields part of this issue - the embedded fields are showing up if it is an object but if we have an array of objects I'm not sure if it will work (if it will then it would still be nice to have the :array designation appended to both fields.)

I'm not sure if there is an example of this in the current master but check out the targeted_regions property in the experiment_capture_c.json on the add_capture_hic branch to see what I mean about an array of objects.  

The field labels generated are: targeted_regions.target and targeted_regions.oligo_file
but the property itself is an array of objects with those 2 fields.  So I don't think making 2 arrays - one in each field - will do what we want unless you already cleverly anticipated this and associations are made between the 2 fields as part of the import_data.py?

**Comment by KorayKirli** [comment]
@j1z0, it would be great if we can add the magic too. I prepared an example called Test_LabUserAward.xls. import_data.py will load User first, than award, and lab.
When it creates the user, it will need to skip 2 fields listed below.

skip = [
          ["user", "submits_for"],
          ["user", "lab"]
]

**Comment by KorayKirli** [comment]
@j1z0 It turns out lab award pi is a bad example for this problem, none of them has the alias, so it is pretty tricky to reference the posted items immediately. One needs to post first, and then go and pick the uuids for each user, and then patch with this values. I will prepare another example.

**Comment by KorayKirli** [comment]
You can use the example /Rao_et_al_2014/test_file_relations.xls
```
skip=[
    ["file", "related_files.relationship_type"],
    ["file","related_files.file"]
]
```

**Comment by KorayKirli** [comment]
The way i suggested requires all "aliases" to be filled. Alternative would be grabbing uuids after posting and put it to second excel for patching.
