### ISSUE TITLE
Tidy Publication schema

### ISSUE THREAD

**Issue by KorayKirli** [4dn-dcic/fourfront#187]
Since we inherited publication schema from Encode without much modification, there are some fields that needs make up.
1) date submitted is a string
2) I think the supplementary data fields is too complicated, and all can be associated in the form of experiments, or documents.
3) Types of publication can be aggregated under 3, 4 categories, instead of >10.
4) I am not sure if we want things like "date revised"
5) Published by is an array, and does not contain anything we need.

I will implement the changes after discussing with @aschroed

**Comment by aschroed** [comment]
1. I don't see this field.  I see date_pubilshed and date_revised.  I agree that these type of fields should be date-time.  
2. I agree but we may want url as well if we are dealing with some 'external' publications.
3. Agreed
4 and 5. I think Nils may have thoughts on some of this as well as necessary status fields as he is involved in setting publication and data release policy and also is interested in using our system as a possible publication tracking tool.  

I have a couple other possible modifications.  We can discuss tomorrow.

**Comment by KorayKirli** [comment]
It is date published that is string.
I agree, we can keep the url.
I guess the date revised that Nils wants is different than the one it refers to now. Most of the fields we ask for can be filled in an automated way just by the pubmed id.

**Comment by aschroed** [comment]
Agreed on the automated filling using PMID if the paper has already been published.  However, I believe Nils' use cases are for consortium members planning and tracking their publications through the complete process of conceiving the idea of publishing on a set of experiments through developing an abstract (though when I wrote papers this was the last thing I did - just saying) and then the full life cycle of submitting, revising and then finally publishing. 

He has got feedback that some people will be leary about sharing details of publications that are in preparation if everyone can see them - hence the need for permission control via status on Publication.  

I agree that published_by does not need to be an array and I think that you are correct that we can remove this and just use 'project' in the Award to indicate who to attribute the publication to i.e. 4DN or External.

**Comment by KorayKirli** [comment]
**Changes Summary** 
All changes are under bestseller branch "PublicationMadeSimple"

**1) Required**
Lab and Award not required (to be able to related external publications)

**2) IdentifyingProperties**
I took out title, for 2 reasons
. the title might change for publications in process
. it is a very long string to use as an id

**3) Authors**
gave a definition for naming convention 
Name1 Surname1, Name2 X. Surname2,...
We can also add a regex, right now it is a string

**4) Contact author**
If the publication is progress, a user will be linked to the publication as the contact person as suggested by @ngehlenborg .(not the corresponding author) 

**5) Supplementary data**
deleted

**6) URL**
added as string, I think we should have this as a calculated property from PMID

**7) Details**  (issue volume page)
I took out this fields, if we want to display such fields in the frond end, we can either create calculated properties or directly add them in the frond end by fetching them from pubmed.

**8) Identifiers**
I reduced them to PMID, I think this is the most capable one, if we need DOI we can also have a calculated property

**9) Categories**
The categories contained the following, is an array, I would say we should go through the list and  reduce the number of options. Maybe @burakalver can have a look.
- "human disease",
- "basic biology",
- "software tool",
-                     "database",
-                     "integrative analysis",
-                     "technology development",
-                     "data standard",
-                     "key publication",
-                     "pilot phase publication",
-                     "model organism biology",
-                     "tutorial",
-                     "genomic annotations",
-                     "production"

**10) Published by**
The list contained the ENCODE related ones, right now we have
- 4DN
- External

**11)Abstract**
Abstract has "rdfs:subPropertyOf": "dc:abstract", I left it there, but have no idea what it does.

**12)Date revised**
deleted

13) Date published
changed from free string to format=date and also added a description 
there is a calculated property publication year, which uses date published. it is modified to work again with the new format

**14)Internal tracking/creation date and last modification date**
I think all these are calculated fields that will come with the tracking system
I did not implement them

**15) Status**
There is the mixin status, and also the publication status. They are both called status at the moment. Since this is related to permissions, I leave this part to @aschroed. I am tempted to call the publication status with some other name and have 2 status.
