### ISSUE TITLE
Modular File schema 

### ISSUE THREAD

**Issue by KorayKirli** [4dn-dcic/fourfront#197]
Our file schema is getting pretty crowded
right now we have around 30 fields which 5 belongs to raw file fastq (like read length, flowcell ...).  
This schema will be used by fastq files, processed files and also other types of raw files like microscopy files. 

 Shall we think of a way like we did with experiments to create modular structures and separate schemas for different file types to be able to simplify the fields?

**Comment by aschroed** [comment]
I think that is a good idea.  The only concern I have is making sure that file upload and download can work fairly seamlessly regardless of file type.  If we can ensure that this will be true without needing extensive modification and customization of the infrastructure components (i.e. scripts) then we should make it so.  From what I understand that should be possible but until we get the file upload working smoothly we should proceed with caution.
