### ISSUE TITLE
cleanup Wrangler Repo

### ISSUE THREAD

**Issue by j1z0** [4dn-dcic/fourfront#198]
it's kinda a mess we need to do the following:
- [ ] rename all the functions to something meaningful
- [ ] add tests
- [ ] add coverage
- [ ] add linter
- [ ] make public and hook up to travis
- [ ] hook up to codacy
- [ ] hook up to coveralls
- [ ] integration importing files as part of beanstalk deployment to development (for additional testing and to get data on development instance)

**Comment by KorayKirli** [comment]
I renamed the following in the 4DNwranglerTools branch "rename", and checked both get fields and import data for function.
encodedcc & encodedcc to **fdnDCIC**
ENC and ENCODE to **FDN**
