### ISSUE TITLE
Add property 'comment' for tips for data entry

### ISSUE THREAD

**Issue by aschroed** [4dn-dcic/fourfront#199]
As I have been curating the Sanford et al. paper I've noticed that even though I am quite familiar with the schema that when presented with a field name and it's description sometimes it is not enough to quickly clue me in to as if the field requires an identifier for an embedded Item or a string or what?  Maybe this is due to bad descriptions but I think sometimes we want the description that a web viewing user sees to be different than a 'full' description that would be useful for a data submitter.  

An example in the modification schema:

```
"target_of_mod": {
            "title": "Target of Modification",
            "description": "The targeted gene or genomic region that is targeted by the modification.",
            "type": "string",
            "linkTo": "Target"
        },
```

From the description, even though the title starts with 'Target ...', I wasn't positive that a Target Identifier was the appropriate thing to enter - by mistake I might have entered a genomic_region identifier or gene symbol if I was a naive user.

I was thinking that if we used a semi-structured format in the 'comment' field - something like:

```
"target_of_mod": {
            "title": "Target of Modification",
            "description": "The targeted gene or genomic region that is targeted by the modification.",
            "comment": "Item=Target - identifier"
            "type": "string",
            "linkTo": "Target"
        },
```

and included that info in the excel worksheet as another row then it would be explicit for someone either filling in the sheet or using it for references as they make a scripted submission.

If people think this is a worthwhile idea then we can make some sub tasks to add 'comments' to the schemas where it make sense.

In a 4DNWranglersTools branch 'add_comment_row' I've made modifications to:
 get_field_info.py to fill in the extra row to the sheets if you provide the --comments arg import_data.py to by default now skip the first 4 rows of the sheets and also allow the user to enter a value for the number of rows to skip in case they want to insert a row or two for themselves for their own reference --skiprows 5 or if they are using sheets from before the comment row was added so they only want to skip 3 i.e. --skiprows 3

Again if we decide this is a good idea I will make a pull request

**Comment by j1z0** [comment]
Hey the only think I would suggest is to not use the comment field as that is used for other stuff right?  We could just as easily add a comments-for-submitters field...., but if the comment field isn't really used for other stuff then sure we can add the comment field..

**Comment by aschroed** [comment]
AFAICT comment has  mostly been used for giving tips on acceptable formats or things that are useful for submitting data so this proposal just kind of extends that by making that field visible for submitters.  

As we have building the schemas I have included some internal questions in 'comment' fields on occasion so those should be cleaned up as part of this but otherwise I don't think we need a new field - but it's good of you to make the suggestion that we might want a separate dedicated field for this.

**Comment by KorayKirli** [comment]
I think the 3 rows is already quite detailed. I would suggest to modify the title and the description to make it clear when there is an ambiguity. 

Even if submitter enters such a fields wrong, he/she will get a quite detailed error log with the problematic field name and also entry. If you still think this is not clear, for the liked objects we can add a small trick, on the Enum row (3rd row) we can state that this filed is an linked object. (LinkTo:Target).
