### ISSUE TITLE
submitting an array of aliases

### ISSUE THREAD

**Issue by aschroed** [4dn-dcic/fourfront#201]
Not sure if this is related to #153 or not but I am getting errors when trying to submit an array value with multiple item aliases in it: 

in Biosample sheet -
Field is 'modifications:array'
rows with single values like so ['dcic:clone4_5_6'] import fine.

rows with two values like so ['dcic:clone4_5_6', 'dcic:clone6-2']
give the following warnings indicating validation errors:

WARNING:root:POST failure. Response = {"errors": [{"description": "\"dcic:clone4_5_6'\" not found", "name": ["modifications", 0], "location": "body"}, {"description": "\" 'dcic:clone6-2\" not found", "name": ["modifications", 1], "location": "body"}], "title": "Unprocessable Entity", "status": "error", "code": 422, "@type": ["ValidationFailure", "Error"], "description": "Failed validation"}

This is going on in my add_capture_hic branch while trying to load locally and I haven't yet had time to generate a test case for the beanstalk instance to determine if it is an issue there too.  I will try to do so next week and confirm it's not just me but if @KorayKirli has run across this then input appreciated.

**Comment by KorayKirli** [comment]
You can use the following form, it is simpler to enter. I guess Jeremy fixed this a while ago. Try it in your local and see if it works. That's what I had for multiple files in experiment. For single objects the [] still works but you can loose them too.

dcic:clone4_5_6,dcic:clone6-2

Once our upload file patch update... scripts are finalized, I will write detailed instructions.
