### ISSUE TITLE
add python and js / jsx linters to build process

### ISSUE THREAD

**Issue by j1z0** [4dn-dcic/fourfront#41]
we should be better about code standards, lets add both python and js linters to the build process, with the aim to have them fail the build if standards aren't maintained (depending on how many errors the linters are currently spitting out)

**Comment by KorayKirli** [comment]
I have it on my atom, and was trying to keep up with that. Will it fail if it is a warning (like missing docstring in public class) which we have quite often?

**Comment by j1z0** [comment]
we can tweak / what passes vs what fails… will have to play with the settings a bit to get it working for us.

**Comment by KorayKirli** [comment]
Okay , I will make sure that the types are error free

**Comment by j1z0** [comment]
ok this is now working with codacy.com.  Will hook this up to slack and give everybody an account

**Comment by j1z0** [comment]
linters are in place with reporting here:

https://www.codacy.com/app/jeremy_7/fourfront/dashboard

only remaining issue is I would like to get codecoverage for python into the same place, but that is awaiting this issue:

https://github.com/codacy/python-codacy-coverage/issues/25
