### ISSUE TITLE
Text overruns the bounds of the dropdown

### ISSUE THREAD

**Issue by pkerpedjiev** [4dn-dcic/fourfront#489]
![image](https://user-images.githubusercontent.com/2143629/27240103-85f2749a-52a1-11e7-97b8-3620dd96f702.png)

**Comment by alexkb0009** [comment]
Thanks! Added `text-overflow: ellipsis` & `overflow:hidden` CSS rules.

Do you think it'd be worth effort to increase height of button if text would overflow (+ ellipsis if would be more than 2 or 3 lines)? Currently, overflowing would likely only happen for that screen size but unsure of possibility of having a long property name eventually which might overflow on a larger screen.

(Not yet in master -)
![Text Ellipsis Example](https://i.gyazo.com/a90988a588e099a8182aed8a708d53ab.png)
